version: '3.9'

services:
  postgres_db:
    image: postgres:15
    container_name: dzencode_postgres
    volumes:
      - ~/.pg/pg_data/super_user:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
  dZENcode:
    build: .
    image: dzencode_docker:latest
    container_name: dzencode_docker
    depends_on:
      - postgres_db
      - redis
    volumes:
      - static_volume:/super_user/static2
      - media_volume:/super_user/media
    environment:
      DJANGO_SETTINGS_MODULE: "${DJANGO_SETTINGS_MODULE}"
    command: >
      bash -c "./manage.py collectstatic --noinput && ./manage.py makemigrations && ./manage.py migrate && uvicorn config.asgi:application --host 0.0.0.0 --port 8000"    
  redis:
    image: redis:5
    container_name: dzencode_redis
    ports:
      - "6379:6379"


volumes:
  static_volume:
  media_volume:

  # nginx:
  #   build:
  #     dockerfile: ./Dockerfile
  #     contaxt: ./docker/nginx 
  #   container_name: dzencode_nginx
  #   image: dzencode_nginx
  #   volumes:
  #     - static_volume:/super_user/static2
  #     - media_volume:/super_user/media
  #   depends_on:
  #     - dZENcode
  #   ports:
  #     - "80:80"